# Generated by Django 2.2.8 on 2019-12-06 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostFlight',
            fields=[
                ('transport_date', models.DateField(default=datetime.date(2019, 11, 1))),
                ('flight_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('base', models.CharField(default='', max_length=100)),
                ('transport_type', models.CharField(default='', max_length=100)),
                ('tail_num', models.CharField(default='', max_length=50)),
                ('med_crew_1', models.CharField(default='', max_length=100)),
                ('activity_flight', models.CharField(default='', max_length=100)),
                ('scene_hosp', models.CharField(default='', max_length=100)),
                ('assigned_time', models.TimeField(blank=True, default='00:00')),
                ('lift_time', models.TimeField(blank=True, default='00:00')),
                ('at_recieving_time', models.TimeField(blank=True, default='00:00')),
                ('at_patient_time', models.TimeField(blank=True, default='00:00')),
                ('depart_recieving_time', models.TimeField(blank=True, default='00:00')),
                ('ifr_vfr', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
