# Generated by Django 2.2.8 on 2019-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflight', '0003_postflight_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='postflight',
            name='dispatch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
