# Generated by Django 2.2.8 on 2019-12-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflight', '0004_postflight_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='postflight',
            name='aviation_issues',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='postflight',
            name='aviation_issues_comments',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='postflight',
            name='maintenance_issues',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='postflight',
            name='weather_issues',
            field=models.CharField(default='', max_length=100),
        ),
    ]
