# Generated by Django 2.2.8 on 2019-12-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postflight', '0005_auto_20191207_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postflight',
            old_name='at_recieving_time',
            new_name='at_sending_time',
        ),
        migrations.RenameField(
            model_name='postflight',
            old_name='depart_recieving_time',
            new_name='depart_sending_time',
        ),
    ]
