# Generated by Django 2.2.8 on 2019-12-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postflight', '0006_auto_20191207_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='postflight',
            name='severity_index',
            field=models.CharField(default='', max_length=100),
        ),
    ]
